version: '3.6'
services:

  es01:
    image: elasticsearch:8.15.0
    environment:
      - cluster.name=elastic-cluster
      - node.name=es01
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --user $$ELASTIC_USERNAME:$$ELASTIC_PASSWORD http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    networks:
      - backend

  setup:
    image: elasticsearch:8.15.0
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        echo "Setting kibana_system password";
        until curl -s -X POST -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" http://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - backend

  kibana:
    image: kibana:8.15.0
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    depends_on:
      - setup
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - backend


volumes:
  es_data01:
  kibana_data:

networks:
  backend:
    driver: bridge
