version: '3.6'
services:

  es01:
    image: elasticsearch:8.15.0
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --user $$ELASTIC_USERNAME:$$ELASTIC_PASSWORD http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 100
    ports:
      - 9200:9200
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    networks:
      - backend

  es02:
    image: elasticsearch:8.15.0
    environment:
      - node.name=es02
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --user $$ELASTIC_USERNAME:$$ELASTIC_PASSWORD http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 100
    volumes:
      - es_data02:/usr/share/elasticsearch/data
    networks:
      - backend

  es03:
    image: elasticsearch:8.15.0
    environment:
      - node.name=es03
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --user $$ELASTIC_USERNAME:$$ELASTIC_PASSWORD http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 100
    volumes:
      - es_data03:/usr/share/elasticsearch/data
    networks:
      - backend

  kibana:
    image: kibana:8.15.0
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
    depends_on:
      es01:
        condition: service_healthy
      es02:
        condition: service_healthy
      es03:
        condition: service_healthy
    ports:
      - 5601:5601
    volumes:
      - kibana_data:/usr/share/kibana/data
    networks:
      - backend


volumes:
  es_data01:
  es_data02:
  es_data03:
  kibana_data:

networks:
  backend:
    driver: bridge
